# Generated by Django 3.1.7 on 2021-04-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_auto_20210427_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger')], default='primary', max_length=100),
            preserve_default=False,
        ),
    ]
