# Generated by Django 3.1.7 on 2021-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
