# Generated by Django 3.1.7 on 2021-04-30 16:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_item_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ShowCastToCustomers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
