# Generated by Django 3.1.7 on 2021-05-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_auto_20210430_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
