# Generated by Django 3.1.7 on 2021-05-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_auto_20210502_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
