# Generated by Django 3.1.7 on 2021-05-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_auto_20210505_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='actual_balance',
        ),
    ]
