# Generated by Django 3.1.7 on 2021-05-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0012_remove_wallet_actual_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='updated_at',
        ),
    ]
